name: Build and Deploy

on:
  push:
    branches:
      - main   # or your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step: Generate config.js with secret API key
      - name: Create config.js
        run: |
          
          echo "const API_KEY = '${{ secrets.GOOGLE_BOOKS_API_KEY }}';" > js/config.js

      # Step: Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
